version: '3.8'

services:
  fastapi-app:
    container_name: bukencoaching-fastapi-app
    build: .
    image: fast_api_base

    env_file:
      - .env
    ports:
      - "4004:4004"
    volumes:
      - .:/app
    depends_on:
      - db
    command: "uvicorn app.main:app --host 0.0.0.0 --port 4004 --reload"

  db:
    container_name: bukencoaching_postgresql_db
    image: postgres:16

    ports:
      - "5005:5005"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_DB_DRIVER=pgsql
    depends_on:
      - db


volumes:
  postgres_data: